// <auto-generated />
namespace BookMyRide.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V002));
        
        string IMigrationMetadata.Id
        {
            get { return "201808270817404_V.0.02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
